package ir.ac.kntu.delivery;

public enum Address {
    SAADATABAD(14),VALIASR(4),KAREGAR(4),SHARIATI(13),FELESTIN(2),
    FERDOSI(3),MOLAVI(7),SARDARJANGAL(16),SADEGHIYEH(8),PUNAK(15),
    TAJRISH(15),NARMAK(18),TEHRANPARS(15),BAHARESTAN(5),AZARBAYJAN(1),
    AZADI(6), AZARI(9), MEHRABAD(16), FERDOWS(3),MIRDAMAD(12),
    GISHA(7), JANNATABAD(18), ELAHIYEH(17), DARROUS(15), JORDAN(14),
    PASDARAN(15), DAVOODIYEH(13), VANAK(11), EKHTIARIEH(19),  FARAHZAD(16),
    CHITGAR(24), CHIZAR(18), ABDOLABAD(16), YAKHCHIABAD(13), JAVADIYEH(8),
    NAZIABAD(10), JEY(5), TARASHT(7), TEHRANSAR(15), SHAHRARA(5),
    APADANA(8), AMIRABAD(7), SATARKHAN(6), MEHRAN(12), SHAHRAN(17),
    EVIN(17), DARAKEH(18), DARBAND(19), OZGOL(20), AJUDANIYE(20),
    NIAVARAN(21), JAMARAN(20), ZAFARANIYEH(19), JAMALZADEH(2), JOMHOURI(2),
    QEZELQALEH(6), EIVANAK(12), MAHMODIYEH(16), DEZASHIB(17), KASHANAK(20),
    DARABAD(21), QEYTARIEH(15), SOHANAK(21), FERESHTEH(16), DIBAJI(18),
    FARMANIEH(18), KAMRANIYEH(18), KOHSAR(17), TEHRANVILA(7), PARDISAN(13),
    TEYMOORI(7), BEHBOODI(4), JALALALAHMAD(4), SHADEMAN(5), MARZDARAN(9),
    ARARAT(12), SEYYEDKHANDAN(12), QOLHAK(16), JOLFA(13), ZAFAR(12),
    MOLLASADRA(11), MAJIDIYEH(10), LAVIZAN(19), DELAVARAN(10), HERAVI(15),
    ANDISHEH(18), ERAM(13), ABOZAR(12), EKBATAN(11), SHAHIN(17),
    SINDOKHT(3), GANDHI(9), SAEI(7), ARGANTIN(9), HAFEZ(11),
    ZARTOSHT(9), TALEGHANI(3), FATEMI(3), NEZAMABAD(7), SOHREVARDI(8),
    MADAEN(12), HAFTHOWZ(12), SABALAN(11), OSTADMOEIN(6), FATH(16),
    BERYANAK(6), SALSABIL(6), JEYHOON(4), MONIRIYEH(2), HOR(2),
    PASTEUR(2), PAMENAR(5), AMINHOZOUR(5), PIROOZI(9), ASHTIANI(5),
    NIROOHAVAYI(11), KHAVARAN(9), NABARD(18), SHOOSH(7), AFSARIYEH(17),
    YAFTABAD(12), KHANIABAD(6), ENGHELAB(0);  // all distance calculate from Enghelab

    private final int distance;

    Address(int distance){
        this.distance = distance;
    }

    public int getDistance() {
        return distance;
    }
}
